#version 450

#include "yave.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0) uniform sampler2D in_color;

layout(rgba8, set = 0, binding = 1) uniform writeonly image2D out_color;

const float gamma = 2.2;

void main() {
	ivec2 coord = ivec2(gl_GlobalInvocationID.xy);

	vec4 color = texelFetch(in_color, coord, 0);

	vec4 inv_gamma = vec4(1.0 / gamma);

	imageStore(out_color, coord, pow(color, inv_gamma));
}


