#version 450

#include "lib/surfels.glsl"

// -------------------------------- I/O --------------------------------

layout(local_size_x = 8, local_size_y = 8) in;

layout(r64ui, set = 0, binding = 0) uniform u64image3D out_probes;


// -------------------------------- MAIN --------------------------------

void main() {
    const uint max_val = floatBitsToUint(max_float);
    imageStore(out_probes, ivec3(gl_GlobalInvocationID), pack_64(uvec2(max_val, max_uint)).xxxx);
}

