#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0) uniform sampler2D in_color;
layout(rgba8, set = 0, binding = 1) uniform writeonly image2D out_color;

void main() {
	ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
	vec2 uv = vec2(gl_GlobalInvocationID.xy) / vec2(gl_NumWorkGroups.xy * gl_WorkGroupSize.xy);

	vec4 color = texture(in_color, uv);
	imageStore(out_color, coord, vec4(color.rgb, 1));
}


